### ISSUE TITLE
Issue with the latest version (v1.0.0)

### ISSUE THREAD

**Issue by Papucs1432** [xHyroM/NexusBlock#6]
Hi, i would like to report an issue with the latest version of the plugin.

The server doesn't load the plugin before version 1.18, is there any ways to fix this please?

**Comment by xHyroM** [comment]
> Hi, i would like to report an issue with the latest version of the plugin.
> 
> The server doesn't load the plugin before version 1.18, is there any ways to fix this please?

Please send server log and what is your server version?

**Comment by Papucs1432** [comment]
Thanks for answering! Here are the server logs of loading the plugin:
https://mcpaste.io/83c18fdde31db7ce
The server is on 1.16.5 with Paper.

**Comment by xHyroM** [comment]
Oh, its because in plugin.yml i have api-version: 1.18

**Comment by xHyroM** [comment]
@Papucs1432 please, can you try https://github.com/xHyroM/NexusBlock/suites/6980850633/artifacts/273044194 build?

**Comment by Papucs1432** [comment]
Sorry, for not responsing. I tested the build you sent, and it still shows an error.
It loads, but later it disables, because of this error:


[10:35:17] [Server thread/INFO]: Enabling NexusBlock v1.1.1
[10:35:17] [Server thread/ERROR]: Error occurred while enabling NexusBlock v1.1.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "xhyrom.nexusblock.structures.holograms.HologramInterface.createHologram(org.bukkit.Location, int, double)" because "xhyrom.nexusblock.NexusBlock.getInstance().hologram" is null
	at xhyrom.nexusblock.structures.Nexus.<init>(Nexus.java:54) ~[?:?]
	at xhyrom.nexusblock.utils.Loader.loadBlocks(Loader.java:44) ~[?:?]
	at xhyrom.nexusblock.NexusBlock.onEnable(NexusBlock.java:37) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-"fa1a7c180"]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[10:35:17] [Server thread/INFO]: Disabling NexusBlock v1.1.1

**Comment by Papucs1432** [comment]
Sorry, for not responsing. I tested the build you sent, and it works.
Thanks for your help! 

But i noticed an error with the files.
A file with "NexusBlock\database.json" appears in the "plugins" folder and not the Nexusblock folder, and you fix this, too?

**Comment by Papucs1432** [comment]
and the color codes don't show up 
![image](https://user-images.githubusercontent.com/89704731/174477564-2f8d199d-6874-4118-b9c0-28e718fd5314.png)

**Comment by xHyroM** [comment]
Do you use decent holograms?

**Comment by Papucs1432** [comment]
no, i use Holographic Displays

**Comment by xHyroM** [comment]
then try to use § in configuration

**Comment by Papucs1432** [comment]
okay, it's working thanks for good support! :)
